[package]
name = "dumbdb"
version = "0.1.0"
edition = "2021"
authors = ["Anon Ray <rayanon004@gmail.com>"]

[dependencies]
anyhow = "1.0.89"
csv = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
